[project]
name = "SICK"
version = "0.1"

dependencies = []

[tool.setuptools]
packages = ["data", "model", "sick_src", "test", "web_app"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

